TO_VALIDATE: True
PATHS:
  PATH_DATA_ROOT: "F:/Datasets/EgoAction/"
  PATH_LABELS_ROOT: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/annotations/labels_train_test/"
  DATASET_SOURCE: "D2"
  DATASET_TARGET: "D1"
  PATH_DATA_SOURCE: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/frames_rgb_flow/feature/"
  PATH_DATA_TARGET: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/frames_rgb_flow/feature/"
  TRAIN_SOURCE_LIST: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/annotations/labels_train_test/epic_D2_train.pkl"
  TRAIN_TARGET_LIST: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/annotations/labels_train_test/epic_D1_train.pkl"
  VAL_DATASET_SOURCE: "D2"
  VAL_DATASET_TARGET: "D1"
  PATH_VAL_DATA_SOURCE: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/frames_rgb_flow/feature/"
  PATH_VAL_DATA_TARGET: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/frames_rgb_flow/feature/"
  VAL_SOURCE_LIST: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/annotations/labels_train_test/epic_D2_train.pkl"
  VAL_TARGET_LIST: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/annotations/labels_train_test/epic_D1_train.pkl"
  TEST_LIST: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/annotations/labels_train_test/epic_D1_test.pkl"
  PATH_EXP: "model/epic/d22d1/"
DATASET:
  DATASET: "epic"
  MODALITY: "RGB"
#  NUM_CLASSES: 97,300
  NUM_SOURCE: 3245
  NUM_TARGET: 1978
  NUM_SEGMENTS: 16
  VAL_SEGMENTS: 16
TRAINER:
  MAX_EPOCHS: 30
  TRAIN_METRIC: "verb"
  BATCH_SIZE: [16,10,16]
TESTER:
  TEST_TARGET_DATA: "F:/Datasets/EgoAction/EPIC/EPIC_KITCHENS_2018/frames_rgb_flow/feature/"
  TEST_SEGMENTS: 16
  BATCH_SIZE: 16