TO_VALIDATE: True
PATHS:
  PATH_DATA_ROOT: "F:/Datasets/EgoAction/"
  PATH_LABELS_ROOT: "F:/Datasets/EgoAction/ADL/annotations/labels_train_test/"
  DATASET_SOURCE: "P_04"
  DATASET_TARGET: "P_11"
  PATH_DATA_SOURCE: "F:/Datasets/EgoAction/ADL/frames_rgb_flow/feature/"
  PATH_DATA_TARGET: "F:/Datasets/EgoAction/ADL/frames_rgb_flow/feature/"
  TRAIN_SOURCE_LIST: "F:/Datasets/EgoAction/ADL/annotations/labels_train_test/adl_P_04_train.pkl"
  TRAIN_TARGET_LIST: "F:/Datasets/EgoAction/ADL/annotations/labels_train_test/adl_P_11_train.pkl"
  VAL_DATASET_SOURCE: "P_04"
  VAL_DATASET_TARGET: "P_11"
  PATH_VAL_DATA_SOURCE: "F:/Datasets/EgoAction/ADL/frames_rgb_flow/feature/"
  PATH_VAL_DATA_TARGET: "F:/Datasets/EgoAction/ADL/frames_rgb_flow/feature/"
  VAL_SOURCE_LIST: "F:/Datasets/EgoAction/ADL/annotations/labels_train_test/adl_P_04_train.pkl"
  VAL_TARGET_LIST: "F:/Datasets/EgoAction/ADL/annotations/labels_train_test/adl_P_11_train.pkl"
  TEST_LIST: "F:/Datasets/EgoAction/ADL/annotations/labels_train_test/adl_P_11_test.pkl"
  EXP_PATH: "model/adl/p42p11/"
DATASET:
  DATASET: "adl"
  MODALITY: "RGB"
#  NUM_CLASSES: 97,300
  NUM_SOURCE: 712
  NUM_TARGET: 527
  NUM_SEGMENTS: 16
  VAL_SEGMENTS: 16
TRAINER:
  MAX_EPOCHS: 30
  TRAIN_METRIC: "verb"
  BATCH_SIZE: [16,12,16]
TESTER:
  TEST_TARGET_DATA: "F:/Datasets/EgoAction/ADL/frames_rgb_flow/feature/"
  TEST_SEGMENTS: 16
  BATCH_SIZE: 16